# Generated by Django 5.2.5 on 2025-08-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bliss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloco', models.CharField(max_length=20)),
                ('unidade', models.CharField(max_length=20)),
                ('garagem', models.CharField(blank=True, max_length=20, null=True)),
                ('situacao', models.CharField(max_length=30)),
                ('valor_tabela', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cliente', models.CharField(blank=True, max_length=100, null=True)),
                ('corretor', models.CharField(blank=True, max_length=100, null=True)),
                ('data_venda', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
