# Generated by Django 5.2.5 on 2025-08-08 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bliss', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bliss',
            old_name='corretor',
            new_name='email',
        ),
        migrations.AddField(
            model_name='bliss',
            name='area_privativa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bliss',
            name='area_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='bliss',
            name='deposito',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bliss',
            name='perc_permuta',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='bliss',
            name='tipologia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bliss',
            name='valor_tabela',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='bliss',
            name='valor_venda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
