# Generated by Django 5.2.5 on 2025-08-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bliss', '0002_rename_corretor_bliss_email_bliss_area_privativa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bliss',
            name='garagem',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
